version: '3.8'

services:
  mongo_db:
    image: mongo:6.0.13-jammy
    restart: always
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    env_file:
      - backend/settings/.env

  web:
    image: vbamnup/mcalendar_backend:v0.3
    restart: always
    ports:
     - "8000:8000"
    volumes:
      - backend:/calendar_backend
    depends_on:
      - mongo_db
    env_file:
      - backend/settings/.env

  # redis:
  #   image: redis:alpine3.17
  #   restart: always
  #   ports:
  #    - "6379:6379"
  #   depends_on:
  #     - web

volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb:
  mongoconfig:
  backend:
#  img:
#  templates: