repos:
  - repo: local
    hooks:
      # Run the formatter.
      - id: ruff-fix
        name: ruff
        entry: ruff --fix
        language: system
        types: [ python ]

      - id: ruff-format
        name: ruff
        entry: ruff format
        language: system
        types: [ python ]

#      - id: black
#        name: black
#        entry: black --config ./pyproject.toml .
#        language: system
#        types: [ python ]
#        pass_filenames: false